name: Build pawncc for Linux ARM64

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            cmake \
            make

      - name: Clone pawn compiler source
        run: |
          git clone https://github.com/Zeex/pawn.git
          cd pawn
          git checkout tags/v3.10.8

      - name: Configure CMake (ARM64)
        run: |
          mkdir -p pawn/build
          cd pawn/build
          cmake ../source/compiler \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_C_FLAGS=-static

      - name: Build pawncc
        run: |
          cd pawn/build
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pawncc-linux-aarch64
          path: pawn/build/pawncc
