name: Build Pawn compiler (Linux aarch64)

on:
  workflow_dispatch:           # manual trigger
  push:
    tags:
      - v3.10.8                # or any tag you want to build automatically

jobs:
  build:
    runs-on: ubuntu-latest     # GitHub-hosted x86_64 runner

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: v3.10.8           # exact tag

    - name: Set up cross-toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        sudo ln -sf /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1 || true

    - name: Configure build
      run: |
        mkdir build && cd build
        cmake ../source/compiler \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/install

    - name: Build
      working-directory: build
      run: make -j$(nproc)

    - name: Install / stage
      working-directory: build
      run: make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pawn-compiler-aarch64-v3.10.8
        path: |
          build/install/bin/pawncc
          build/install/lib/libpawnc.so
          build/install/bin/pawndisasmsm
        retention-days: 90
