name: Build Pawn compiler (Linux aarch64)

on:
  workflow_dispatch:
  push:
    tags:
      - v3.10.8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone upstream repo + checkout tag v3.10.8
      run: |
        git clone --depth 1 --branch v3.10.8 https://github.com/pawn-lang/compiler.git ~/pawn
        cd ~/pawn

    - name: Install cross toolchain
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Configure & build
      working-directory: ~/pawn
      run: |
        mkdir build && cd build
        cmake ../source/compiler \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/install
        make -j$(nproc)

    - name: Install binaries
      working-directory: ~/pawn/build
      run: make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pawn-compiler-aarch64-v3.10.8
        path: |
          ~/pawn/build/install/bin/pawncc
          ~/pawn/build/install/lib/libpawnc.so
          ~/pawn/build/install/bin/pawndisasmsm
        retention-days: 90
